project:
  type: website
  output-dir: docs

website:
  title: "Tracking COVID-19"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/am0505/tracking_covid
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: litera
    css: styles.css

editor: visual

