project:
  type: website
  output-dir: docs

website:
  title: "Tracking COVID-19"
  site-url: https://www.am0505.github.io
  description: "A repository for documenting research related to COVID-19"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/am0505/tracking_covid
      - icon: twitter
        href: https://twitter.com/
      - icon: rss
        href: index.xml
format:
  html:
    theme: Flatly
    css: styles.css

editor: visual

